### ISSUE TITLE
Home > Household > Plasticware

### ISSUE THREAD

**Issue by adtac** [SuganPrabu96/fruitSalad#2]
There is a item called "... dustbin". When I click add to cart, I am getting a qty popup that has 0.5, 1, 1.5, 2, ...
It should only contain 1, 2, 3, 4, ...
This problem may occur in other stuff as well. The dustbin-thing is the page I found the bug in the first place.

**Comment by ssrikrishna96** [comment]
I checked the dustbin item! Value of cb is 'y' ! So its a backend mistake !

**Comment by SuganPrabu96** [comment]
Fixed in backend. Working now
