### ISSUE TITLE
My cart - quantity

### ISSUE THREAD

**Issue by adtac** [SuganPrabu96/fruitSalad#7]
Not exactly an issue, just a suggestion.
If I buy 4 Britannia 50-50, instead of saying 4.0 \* 100 gm, just say Quantity: 4. Or a big bold " X 4 ". In the current model the quantity is not very clear.

**Comment by SuganPrabu96** [comment]
Changed the layout. Need to implement edit and remove features

**Comment by SuganPrabu96** [comment]
Done
